WIP: Initial commit for upgrades
oracle/spring-cloud-oci pull request #36
Opened 2024-05-09 18:43 UTC by andytael

Upgrades to resolve some CVEs

2024-05-14 20:25 UTC, markxnelson requested changes

2024-05-14 20:25 UTC, markxnelson commented on README.md
> +| 1.0.0           | 2022.0.x, 2023.0.x | 3.2.x, 3.1.x, 3.0.x | 3.41.1       |
i think we should rev it, leave 1.0.0 as it was, and add a 1.1.0 or 1.0.1 with the new stuff

2024-05-14 20:25 UTC, markxnelson commented on pom.xml
> +            <!-- OpenRewrite Plugin
eep

2024-05-14 20:25 UTC, markxnelson commented on pom.xml
> +            <!-- OpenRewrite Plugin
remove this?

2024-05-15 16:51 UTC, andytael commented on README.md
> +| 1.0.0           | 2022.0.x, 2023.0.x | 3.2.x, 3.1.x, 3.0.x | 3.41.1       |
Agreed, added a 1.0.1

2024-05-15 16:52 UTC, andytael commented on pom.xml
> +            <!-- OpenRewrite Plugin
Gone with the wind

2024-05-15 16:54 UTC, markxnelson approved these changes

2024-05-15 16:56 UTC, merged