OKE Workload Identity Authentication
oracle/spring-cloud-oci pull request #40
Opened 2024-06-12 18:05 UTC by anders-swanson

2024-06-12 18:27 UTC, andytael commented on docs/src/main/asciidoc/core.adoc
> +For further details, refer to https://blogs.oracle.com/cloud-infrastructure/post/oke-workload-identity-greater-control-access[OKE Workload Identity Authentication]
Shouldn't we point to the docs instead? https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contenggrantingworkloadaccesstoresources.htm

2024-06-12 20:27 UTC, andytael approved these changes
LGTM

2024-06-14 15:41 UTC, markxnelson requested changes
one minor comment

2024-06-14 15:41 UTC, markxnelson commented on README.md
> +| Spring Cloud OCI 1.1.0 | [Reference Docs](https://oracle.github.io/spring-cloud-oci/1.0.0/reference/html/index.html) | [API Docs](https://oracle.github.io/spring-cloud-oci/1.0.0/javadocs/index.html
well we can add some more stuff, like adb, before we release 1.1.0, right, we revved to 1.1.0-SNAPSHOT, so i'd leave this line out until we do a release

2024-06-14 15:43 UTC, anders-swanson commented on README.md
> +| Spring Cloud OCI 1.1.0 | [Reference Docs](https://oracle.github.io/spring-cloud-oci/1.0.0/reference/html/index.html) | [API Docs](https://oracle.github.io/spring-cloud-oci/1.0.0/javadocs/index.html
Updated!

2024-06-14 15:45 UTC, markxnelson approved these changes

2024-06-14 16:56 UTC, merged